# Ubuntu 16.04
# nvidia/cuda:9.0-base
# https://hub.docker.com/layers/nvidia/cuda/9.0-base/images/sha256-4f7ca42225b5779e5e05cdee23431d633fbce12f12a8b9fb51bbb6bc0040c670?context=explore 
# OS/ARCH: linux/amd64
ARG BASE_CONTAINER=nvidia/cuda:9.0-base
FROM $BASE_CONTAINER

LABEL maintainer="Docker Miner <levizebulon@gmail.com>"
